version: '3.5'
services:
  server:
    container_name: Server
    build:
      context: ../.
      dockerfile: ./server.Dockerfile
    ports:
      - '5555:5555'
    restart: 'always'

  client:
    container_name: Client
    build:
      context: ../.
      dockerfile: ./client.Dockerfile
    restart: 'no' 
    depends_on:
      - server
